export const programmingLanguages: Record<string, string> = {
  js: "JavaScript",
  py: "Python",
  rb: "Ruby",
  java: "Java",
  cpp: "C++",
  csharp: "C#",
  php: "PHP",
  go: "Go",
  swift: "Swift",
  ts: "TypeScript",
  rust: "Rust",
  kotlin: "Kotlin",
  perl: "Perl",
  scala: "Scala",
  lua: "Lua",
  dart: "Dart",
  r: "R",
  elixir: "Elixir",
  sql: "SQL",
  html: "HTML",
  css: "CSS",
  sass: "Sass",
};
